### PR TITLE
update akka seed sbt to latest 1.x

### PR DESCRIPTION
**Pull request by codesurf42**

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @codesurf42,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by raboof** [comment]
(manually checked the CLA is signed, not sure why github isn't showing it)

**Comment by jiminhsieh** [comment]
How about update sbt version of this project too instead of the seed project only?

**Comment by codesurf42** [comment]
Yeah, good idea @jiminhsieh, when I did that giter was not supporting sbt 1.x yet.

**Comment by clemensutschig** [comment]
When will the merge happen - we wait desperately for this for https://github.com/opendevstack

**Comment by raboof** [comment]
Sorry for the wait, thanks for the contribution!

**Pull request merged**
