### PR TITLE
Promote using revolver instead of StdIn.readline

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by raboof** [comment]
Yeah we typically use it in http apps (the plugin is even under `io.spray`), but I'd say it beats `StdIn.readLine()` anywhere ;)

**Comment by ktoso** [comment]
Hmm for advanced users sure, but for someone clueless and coming to Akka for the first time?

**Comment by ktoso** [comment]
I love the plugin, just not sure if this is the best place to put it

**Comment by partounian** [comment]
I am clueless and coming to Akka for the first time and this is not confusing if that helps.

**Comment by partounian** [comment]
Seems like reStart actually does not work. 
```
[error] Not a valid command: reStart
[error] Not a valid project ID: reStart
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: reStart (similar: target, state, startYear)
[error] reStart
[error]        ^
```

**Pull request merged**
