### PR TITLE
Update to sbt 1.3.6 : Correct import statements based on package ente…

### PR DESCRIPTION
**Pull request by gavinbaumanis**
* Upgrade sbt to 1.3.6
* Correct import statements in test to correctly update on the package entered during project creation.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @gavinbaumanis,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by gavinbaumanis** [comment]
Include Scala 2.13.1 in travis config.

**Comment by gavinbaumanis** [comment]
I have signed the CLA

**Comment by raboof** [comment]
Refs #41

**Comment by raboof** [comment]
Looks like the failure was unrelated, #44

**Comment by raboof** [comment]
Sorry for the delay, thanks!

**Pull request merged**
